//
//  CountryBankClass.swift
//  Hangman
//
//  Created by Novica Petrovic on 28/08/2018.
//  Copyright © 2018 Novica Petrovic. All rights reserved.
//

import Foundation

class CountryBankClass  {
    
    var listOfCountries = [SecretWordClass]()
    
    init() {
        
        // A (11 countries)
        listOfCountries.append(SecretWordClass(film: "afghanistan"))
        listOfCountries.append(SecretWordClass(film: "albania"))
        listOfCountries.append(SecretWordClass(film: "algeria"))
        listOfCountries.append(SecretWordClass(film: "andorra"))
        listOfCountries.append(SecretWordClass(film: "angola"))
        listOfCountries.append(SecretWordClass(film: "antigua and barbuda"))
        listOfCountries.append(SecretWordClass(film: "argentina"))
        listOfCountries.append(SecretWordClass(film: "armenia"))
        listOfCountries.append(SecretWordClass(film: "australia"))
        listOfCountries.append(SecretWordClass(film: "austria"))
        listOfCountries.append(SecretWordClass(film: "azerbaijan"))
        
        // B (17 countries)
        listOfCountries.append(SecretWordClass(film: "the bahamas"))
        listOfCountries.append(SecretWordClass(film: "bahrain"))
        listOfCountries.append(SecretWordClass(film: "bangladesh"))
        listOfCountries.append(SecretWordClass(film: "barbados"))
        listOfCountries.append(SecretWordClass(film: "belarus"))
        listOfCountries.append(SecretWordClass(film: "belgium"))
        listOfCountries.append(SecretWordClass(film: "belize"))
        listOfCountries.append(SecretWordClass(film: "benin"))
        listOfCountries.append(SecretWordClass(film: "bhutan"))
        listOfCountries.append(SecretWordClass(film: "bolivia"))
        listOfCountries.append(SecretWordClass(film: "bosnia and herzegovina"))
        listOfCountries.append(SecretWordClass(film: "botswana"))
        listOfCountries.append(SecretWordClass(film: "brazil"))
        listOfCountries.append(SecretWordClass(film: "brunei"))
        listOfCountries.append(SecretWordClass(film: "bulgaria"))
        listOfCountries.append(SecretWordClass(film: "burkina faso"))
        listOfCountries.append(SecretWordClass(film: "burundi"))
        
        // C (15 countries, excluding congo (2 versions, got confused) and cote d'ivoire)
        listOfCountries.append(SecretWordClass(film: "cabo verde"))
        listOfCountries.append(SecretWordClass(film: "cambodia"))
        listOfCountries.append(SecretWordClass(film: "cameroon"))
        listOfCountries.append(SecretWordClass(film: "canada"))
        listOfCountries.append(SecretWordClass(film: "central african republic"))
        listOfCountries.append(SecretWordClass(film: "chad"))
        listOfCountries.append(SecretWordClass(film: "chile"))
        listOfCountries.append(SecretWordClass(film: "china"))
        listOfCountries.append(SecretWordClass(film: "columbia"))
        listOfCountries.append(SecretWordClass(film: "comoros"))
        listOfCountries.append(SecretWordClass(film: "costa rica"))
        listOfCountries.append(SecretWordClass(film: "croatia"))
        listOfCountries.append(SecretWordClass(film: "cuba"))
        listOfCountries.append(SecretWordClass(film: "cyprus"))
        listOfCountries.append(SecretWordClass(film: "czech republic"))
        
        // D (4 countries)
        listOfCountries.append(SecretWordClass(film: "denmark"))
        listOfCountries.append(SecretWordClass(film: "dijbouti"))
        listOfCountries.append(SecretWordClass(film: "dominica"))
        listOfCountries.append(SecretWordClass(film: "dominican republic"))
        
        // E (8 countries)
        listOfCountries.append(SecretWordClass(film: "east Timor"))
        listOfCountries.append(SecretWordClass(film: "ecuador"))
        listOfCountries.append(SecretWordClass(film: "egypt"))
        listOfCountries.append(SecretWordClass(film: "el Salvador"))
        listOfCountries.append(SecretWordClass(film: "equatorial Guinea"))
        listOfCountries.append(SecretWordClass(film: "eritrea"))
        listOfCountries.append(SecretWordClass(film: "estonia"))
        listOfCountries.append(SecretWordClass(film: "ethiopia"))
        
        // F (3 countries)
        listOfCountries.append(SecretWordClass(film: "fiji"))
        listOfCountries.append(SecretWordClass(film: "finland"))
        listOfCountries.append(SecretWordClass(film: "france"))
        
        // G (11 countries)
        listOfCountries.append(SecretWordClass(film: "gambon"))
        listOfCountries.append(SecretWordClass(film: "the gambia"))
        listOfCountries.append(SecretWordClass(film: "georgia"))
        listOfCountries.append(SecretWordClass(film: "germany"))
        listOfCountries.append(SecretWordClass(film: "ghana"))
        listOfCountries.append(SecretWordClass(film: "greece"))
        listOfCountries.append(SecretWordClass(film: "grenada"))
        listOfCountries.append(SecretWordClass(film: "guatemala"))
        listOfCountries.append(SecretWordClass(film: "guinea"))
        listOfCountries.append(SecretWordClass(film: "guinea bissau"))
        listOfCountries.append(SecretWordClass(film: "guvana"))
        
        // H (3 countries)
        listOfCountries.append(SecretWordClass(film: "haiti"))
        listOfCountries.append(SecretWordClass(film: "honduras"))
        listOfCountries.append(SecretWordClass(film: "hungary"))
        
        // I (8 countries)
        listOfCountries.append(SecretWordClass(film: "iceland"))
        listOfCountries.append(SecretWordClass(film: "india"))
        listOfCountries.append(SecretWordClass(film: "indonesia"))
        listOfCountries.append(SecretWordClass(film: "iran"))
        listOfCountries.append(SecretWordClass(film: "iraq"))
        listOfCountries.append(SecretWordClass(film: "ireland"))
        listOfCountries.append(SecretWordClass(film: "israel"))
        listOfCountries.append(SecretWordClass(film: "italy"))
        
        // J (3 countries)
        listOfCountries.append(SecretWordClass(film: "jamaica"))
        listOfCountries.append(SecretWordClass(film: "japan"))
        listOfCountries.append(SecretWordClass(film: "jordan"))
        
        // K (8 countries)
        listOfCountries.append(SecretWordClass(film: "kazakhstan"))
        listOfCountries.append(SecretWordClass(film: "kenya"))
        listOfCountries.append(SecretWordClass(film: "kiribati"))
        listOfCountries.append(SecretWordClass(film: "north korea"))
        listOfCountries.append(SecretWordClass(film: "south korea"))
        listOfCountries.append(SecretWordClass(film: "kosovo"))
        listOfCountries.append(SecretWordClass(film: "kuwait"))
        listOfCountries.append(SecretWordClass(film: "kyrgyzstan"))
        
        // L (9 countries)
        listOfCountries.append(SecretWordClass(film: "laos"))
        listOfCountries.append(SecretWordClass(film: "latvia"))
        listOfCountries.append(SecretWordClass(film: "lebanon"))
        listOfCountries.append(SecretWordClass(film: "lesotho"))
        listOfCountries.append(SecretWordClass(film: "liberia"))
        listOfCountries.append(SecretWordClass(film: "libya"))
        listOfCountries.append(SecretWordClass(film: "liechtenstein"))
        listOfCountries.append(SecretWordClass(film: "lithuania"))
        listOfCountries.append(SecretWordClass(film: "luxembourg"))
        
        // M (19 countries)
        listOfCountries.append(SecretWordClass(film: "macedonia"))
        listOfCountries.append(SecretWordClass(film: "madagascar"))
        listOfCountries.append(SecretWordClass(film: "malawi"))
        listOfCountries.append(SecretWordClass(film: "malaysia"))
        listOfCountries.append(SecretWordClass(film: "maldives"))
        listOfCountries.append(SecretWordClass(film: "mali"))
        listOfCountries.append(SecretWordClass(film: "malta"))
        listOfCountries.append(SecretWordClass(film: "marshall islands"))
        listOfCountries.append(SecretWordClass(film: "mauritania"))
        listOfCountries.append(SecretWordClass(film: "mauritius"))
        listOfCountries.append(SecretWordClass(film: "mexico"))
        listOfCountries.append(SecretWordClass(film: "federate states of micronesia"))
        listOfCountries.append(SecretWordClass(film: "moldova"))
        listOfCountries.append(SecretWordClass(film: "monaco"))
        listOfCountries.append(SecretWordClass(film: "mongolia"))
        listOfCountries.append(SecretWordClass(film: "montenegro"))
        listOfCountries.append(SecretWordClass(film: "morocco"))
        listOfCountries.append(SecretWordClass(film: "mozambique"))
        listOfCountries.append(SecretWordClass(film: "myanmar"))
        
        // N (9 countries)
        listOfCountries.append(SecretWordClass(film: "namibia"))
        listOfCountries.append(SecretWordClass(film: "nauru"))
        listOfCountries.append(SecretWordClass(film: "nepal"))
        listOfCountries.append(SecretWordClass(film: "netherlands"))
        listOfCountries.append(SecretWordClass(film: "new zealand"))
        listOfCountries.append(SecretWordClass(film: "nicaragua"))
        listOfCountries.append(SecretWordClass(film: "niger"))
        listOfCountries.append(SecretWordClass(film: "nigeria"))
        listOfCountries.append(SecretWordClass(film: "norway"))
        
        // O (1 country)
        listOfCountries.append(SecretWordClass(film: "oman"))
        
        // P (10 countries)
        listOfCountries.append(SecretWordClass(film: "pakistan"))
        listOfCountries.append(SecretWordClass(film: "palau"))
        listOfCountries.append(SecretWordClass(film: "panama"))
        listOfCountries.append(SecretWordClass(film: "papa new guinea"))
        listOfCountries.append(SecretWordClass(film: "paraguay"))
        listOfCountries.append(SecretWordClass(film: "peru"))
        listOfCountries.append(SecretWordClass(film: "philippines"))
        listOfCountries.append(SecretWordClass(film: "poland"))
        listOfCountries.append(SecretWordClass(film: "portugal"))
        listOfCountries.append(SecretWordClass(film: "qatar"))
        
        // R (3 countries)
        listOfCountries.append(SecretWordClass(film: "romania"))
        listOfCountries.append(SecretWordClass(film: "russia"))
        listOfCountries.append(SecretWordClass(film: "rwanda"))
        
        // S (26 countries)
        listOfCountries.append(SecretWordClass(film: "saint kitts and nevis"))
        listOfCountries.append(SecretWordClass(film: "saint lucia"))
        listOfCountries.append(SecretWordClass(film: "saint vincent and the grenadines"))
        listOfCountries.append(SecretWordClass(film: "samoa"))
        listOfCountries.append(SecretWordClass(film: "san marino"))
        listOfCountries.append(SecretWordClass(film: "sao tome and principe"))
        listOfCountries.append(SecretWordClass(film: "saudia arabia"))
        listOfCountries.append(SecretWordClass(film: "senegal"))
        listOfCountries.append(SecretWordClass(film: "serbia"))
        listOfCountries.append(SecretWordClass(film: "seychelles"))
        listOfCountries.append(SecretWordClass(film: "sierra leone"))
        listOfCountries.append(SecretWordClass(film: "singapore"))
        listOfCountries.append(SecretWordClass(film: "slovakia"))
        listOfCountries.append(SecretWordClass(film: "slovenia"))
        listOfCountries.append(SecretWordClass(film: "solomon islands"))
        listOfCountries.append(SecretWordClass(film: "somalia"))
        listOfCountries.append(SecretWordClass(film: "south africa"))
        listOfCountries.append(SecretWordClass(film: "spain"))
        listOfCountries.append(SecretWordClass(film: "sri lanka"))
        listOfCountries.append(SecretWordClass(film: "sudan"))
        listOfCountries.append(SecretWordClass(film: "south sudan"))
        listOfCountries.append(SecretWordClass(film: "suriname"))
        listOfCountries.append(SecretWordClass(film: "swaziland"))
        listOfCountries.append(SecretWordClass(film: "sweden"))
        listOfCountries.append(SecretWordClass(film: "switzerland"))
        listOfCountries.append(SecretWordClass(film: "syria"))
        
        // T (11 countries)
        listOfCountries.append(SecretWordClass(film: "taiwan"))
        listOfCountries.append(SecretWordClass(film: "tajikistan"))
        listOfCountries.append(SecretWordClass(film: "tanzania"))
        listOfCountries.append(SecretWordClass(film: "thailand"))
        listOfCountries.append(SecretWordClass(film: "togo"))
        listOfCountries.append(SecretWordClass(film: "tonga"))
        listOfCountries.append(SecretWordClass(film: "trinidad and tobago"))
        listOfCountries.append(SecretWordClass(film: "tunisia"))
        listOfCountries.append(SecretWordClass(film: "turkey"))
        listOfCountries.append(SecretWordClass(film: "turkmenistan"))
        listOfCountries.append(SecretWordClass(film: "tuvalu"))
        
        // U (7 countries)
        listOfCountries.append(SecretWordClass(film: "uganda"))
        listOfCountries.append(SecretWordClass(film: "ukraine"))
        listOfCountries.append(SecretWordClass(film: "united arab emirates"))
        listOfCountries.append(SecretWordClass(film: "united kingdom"))
        listOfCountries.append(SecretWordClass(film: "united states"))
        listOfCountries.append(SecretWordClass(film: "uruguay"))
        listOfCountries.append(SecretWordClass(film: "uzbekistan"))
        
        // V (4 countries)
        listOfCountries.append(SecretWordClass(film: "vanuatu"))
        listOfCountries.append(SecretWordClass(film: "vatican city"))
        listOfCountries.append(SecretWordClass(film: "venezuela"))
        listOfCountries.append(SecretWordClass(film: "vietnam"))
        
        // Y (1 country)
        listOfCountries.append(SecretWordClass(film: "Yemen"))
        
        // Z (
        listOfCountries.append(SecretWordClass(film: "zambia"))
        listOfCountries.append(SecretWordClass(film: "zimbabwe"))
    }
    
}
