//
//  CountryBankClass.swift
//  Hangman
//
//  Created by Novica Petrovic on 28/08/2018.
//  Copyright © 2018 Novica Petrovic. All rights reserved.
//

import Foundation

class CountryBankClass  {
    
    var listOfCountries = [SecretWordClass]()
    
    init() {
        
        // A (11 countries)
        listOfCountries.append(SecretWordClass(title: "afghanistan"))
        listOfCountries.append(SecretWordClass(title: "albania"))
        listOfCountries.append(SecretWordClass(title: "algeria"))
        listOfCountries.append(SecretWordClass(title: "andorra"))
        listOfCountries.append(SecretWordClass(title: "angola"))
        listOfCountries.append(SecretWordClass(title: "antigua and barbuda"))
        listOfCountries.append(SecretWordClass(title: "argentina"))
        listOfCountries.append(SecretWordClass(title: "armenia"))
        listOfCountries.append(SecretWordClass(title: "australia"))
        listOfCountries.append(SecretWordClass(title: "austria"))
        listOfCountries.append(SecretWordClass(title: "azerbaijan"))
        
        // B (17 countries)
        listOfCountries.append(SecretWordClass(title: "the bahamas"))
        listOfCountries.append(SecretWordClass(title: "bahrain"))
        listOfCountries.append(SecretWordClass(title: "bangladesh"))
        listOfCountries.append(SecretWordClass(title: "barbados"))
        listOfCountries.append(SecretWordClass(title: "belarus"))
        listOfCountries.append(SecretWordClass(title: "belgium"))
        listOfCountries.append(SecretWordClass(title: "belize"))
        listOfCountries.append(SecretWordClass(title: "benin"))
        listOfCountries.append(SecretWordClass(title: "bhutan"))
        listOfCountries.append(SecretWordClass(title: "bolivia"))
        listOfCountries.append(SecretWordClass(title: "bosnia and herzegovina"))
        listOfCountries.append(SecretWordClass(title: "botswana"))
        listOfCountries.append(SecretWordClass(title: "brazil"))
        listOfCountries.append(SecretWordClass(title: "brunei"))
        listOfCountries.append(SecretWordClass(title: "bulgaria"))
        listOfCountries.append(SecretWordClass(title: "burkina faso"))
        listOfCountries.append(SecretWordClass(title: "burundi"))
        
        // C (15 countries, excluding congo (2 versions, got confused) and cote d'ivoire)
        listOfCountries.append(SecretWordClass(title: "cabo verde"))
        listOfCountries.append(SecretWordClass(title: "cambodia"))
        listOfCountries.append(SecretWordClass(title: "cameroon"))
        listOfCountries.append(SecretWordClass(title: "canada"))
        listOfCountries.append(SecretWordClass(title: "central african republic"))
        listOfCountries.append(SecretWordClass(title: "chad"))
        listOfCountries.append(SecretWordClass(title: "chile"))
        listOfCountries.append(SecretWordClass(title: "china"))
        listOfCountries.append(SecretWordClass(title: "columbia"))
        listOfCountries.append(SecretWordClass(title: "comoros"))
        listOfCountries.append(SecretWordClass(title: "costa rica"))
        listOfCountries.append(SecretWordClass(title: "croatia"))
        listOfCountries.append(SecretWordClass(title: "cuba"))
        listOfCountries.append(SecretWordClass(title: "cyprus"))
        listOfCountries.append(SecretWordClass(title: "czech republic"))
        
        // D (4 countries)
        listOfCountries.append(SecretWordClass(title: "denmark"))
        listOfCountries.append(SecretWordClass(title: "dijbouti"))
        listOfCountries.append(SecretWordClass(title: "dominica"))
        listOfCountries.append(SecretWordClass(title: "dominican republic"))
        
        // E (8 countries)
        listOfCountries.append(SecretWordClass(title: "east Timor"))
        listOfCountries.append(SecretWordClass(title: "ecuador"))
        listOfCountries.append(SecretWordClass(title: "egypt"))
        listOfCountries.append(SecretWordClass(title: "el Salvador"))
        listOfCountries.append(SecretWordClass(title: "equatorial Guinea"))
        listOfCountries.append(SecretWordClass(title: "eritrea"))
        listOfCountries.append(SecretWordClass(title: "estonia"))
        listOfCountries.append(SecretWordClass(title: "ethiopia"))
        
        // F (3 countries)
        listOfCountries.append(SecretWordClass(title: "fiji"))
        listOfCountries.append(SecretWordClass(title: "finland"))
        listOfCountries.append(SecretWordClass(title: "france"))
        
        // G (11 countries)
        listOfCountries.append(SecretWordClass(title: "gambon"))
        listOfCountries.append(SecretWordClass(title: "the gambia"))
        listOfCountries.append(SecretWordClass(title: "georgia"))
        listOfCountries.append(SecretWordClass(title: "germany"))
        listOfCountries.append(SecretWordClass(title: "ghana"))
        listOfCountries.append(SecretWordClass(title: "greece"))
        listOfCountries.append(SecretWordClass(title: "grenada"))
        listOfCountries.append(SecretWordClass(title: "guatemala"))
        listOfCountries.append(SecretWordClass(title: "guinea"))
        listOfCountries.append(SecretWordClass(title: "guinea bissau"))
        listOfCountries.append(SecretWordClass(title: "guvana"))
        
        // H (3 countries)
        listOfCountries.append(SecretWordClass(title: "haiti"))
        listOfCountries.append(SecretWordClass(title: "honduras"))
        listOfCountries.append(SecretWordClass(title: "hungary"))
        
        // I (8 countries)
        listOfCountries.append(SecretWordClass(title: "iceland"))
        listOfCountries.append(SecretWordClass(title: "india"))
        listOfCountries.append(SecretWordClass(title: "indonesia"))
        listOfCountries.append(SecretWordClass(title: "iran"))
        listOfCountries.append(SecretWordClass(title: "iraq"))
        listOfCountries.append(SecretWordClass(title: "ireland"))
        listOfCountries.append(SecretWordClass(title: "israel"))
        listOfCountries.append(SecretWordClass(title: "italy"))
        
        // J (3 countries)
        listOfCountries.append(SecretWordClass(title: "jamaica"))
        listOfCountries.append(SecretWordClass(title: "japan"))
        listOfCountries.append(SecretWordClass(title: "jordan"))
        
        // K (8 countries)
        listOfCountries.append(SecretWordClass(title: "kazakhstan"))
        listOfCountries.append(SecretWordClass(title: "kenya"))
        listOfCountries.append(SecretWordClass(title: "kiribati"))
        listOfCountries.append(SecretWordClass(title: "north korea"))
        listOfCountries.append(SecretWordClass(title: "south korea"))
        listOfCountries.append(SecretWordClass(title: "kosovo"))
        listOfCountries.append(SecretWordClass(title: "kuwait"))
        listOfCountries.append(SecretWordClass(title: "kyrgyzstan"))
        
        // L (9 countries)
        listOfCountries.append(SecretWordClass(title: "laos"))
        listOfCountries.append(SecretWordClass(title: "latvia"))
        listOfCountries.append(SecretWordClass(title: "lebanon"))
        listOfCountries.append(SecretWordClass(title: "lesotho"))
        listOfCountries.append(SecretWordClass(title: "liberia"))
        listOfCountries.append(SecretWordClass(title: "libya"))
        listOfCountries.append(SecretWordClass(title: "liechtenstein"))
        listOfCountries.append(SecretWordClass(title: "lithuania"))
        listOfCountries.append(SecretWordClass(title: "luxembourg"))
        
        // M (19 countries)
        listOfCountries.append(SecretWordClass(title: "macedonia"))
        listOfCountries.append(SecretWordClass(title: "madagascar"))
        listOfCountries.append(SecretWordClass(title: "malawi"))
        listOfCountries.append(SecretWordClass(title: "malaysia"))
        listOfCountries.append(SecretWordClass(title: "maldives"))
        listOfCountries.append(SecretWordClass(title: "mali"))
        listOfCountries.append(SecretWordClass(title: "malta"))
        listOfCountries.append(SecretWordClass(title: "marshall islands"))
        listOfCountries.append(SecretWordClass(title: "mauritania"))
        listOfCountries.append(SecretWordClass(title: "mauritius"))
        listOfCountries.append(SecretWordClass(title: "mexico"))
        listOfCountries.append(SecretWordClass(title: "federate states of micronesia"))
        listOfCountries.append(SecretWordClass(title: "moldova"))
        listOfCountries.append(SecretWordClass(title: "monaco"))
        listOfCountries.append(SecretWordClass(title: "mongolia"))
        listOfCountries.append(SecretWordClass(title: "montenegro"))
        listOfCountries.append(SecretWordClass(title: "morocco"))
        listOfCountries.append(SecretWordClass(title: "mozambique"))
        listOfCountries.append(SecretWordClass(title: "myanmar"))
        
        // N (9 countries)
        listOfCountries.append(SecretWordClass(title: "namibia"))
        listOfCountries.append(SecretWordClass(title: "nauru"))
        listOfCountries.append(SecretWordClass(title: "nepal"))
        listOfCountries.append(SecretWordClass(title: "netherlands"))
        listOfCountries.append(SecretWordClass(title: "new zealand"))
        listOfCountries.append(SecretWordClass(title: "nicaragua"))
        listOfCountries.append(SecretWordClass(title: "niger"))
        listOfCountries.append(SecretWordClass(title: "nigeria"))
        listOfCountries.append(SecretWordClass(title: "norway"))
        
        // O (1 country)
        listOfCountries.append(SecretWordClass(title: "oman"))
        
        // P (10 countries)
        listOfCountries.append(SecretWordClass(title: "pakistan"))
        listOfCountries.append(SecretWordClass(title: "palau"))
        listOfCountries.append(SecretWordClass(title: "panama"))
        listOfCountries.append(SecretWordClass(title: "papa new guinea"))
        listOfCountries.append(SecretWordClass(title: "paraguay"))
        listOfCountries.append(SecretWordClass(title: "peru"))
        listOfCountries.append(SecretWordClass(title: "philippines"))
        listOfCountries.append(SecretWordClass(title: "poland"))
        listOfCountries.append(SecretWordClass(title: "portugal"))
        listOfCountries.append(SecretWordClass(title: "qatar"))
        
        // R (3 countries)
        listOfCountries.append(SecretWordClass(title: "romania"))
        listOfCountries.append(SecretWordClass(title: "russia"))
        listOfCountries.append(SecretWordClass(title: "rwanda"))
        
        // S (26 countries)
        listOfCountries.append(SecretWordClass(title: "saint kitts and nevis"))
        listOfCountries.append(SecretWordClass(title: "saint lucia"))
        listOfCountries.append(SecretWordClass(title: "saint vincent and the grenadines"))
        listOfCountries.append(SecretWordClass(title: "samoa"))
        listOfCountries.append(SecretWordClass(title: "san marino"))
        listOfCountries.append(SecretWordClass(title: "sao tome and principe"))
        listOfCountries.append(SecretWordClass(title: "saudia arabia"))
        listOfCountries.append(SecretWordClass(title: "senegal"))
        listOfCountries.append(SecretWordClass(title: "serbia"))
        listOfCountries.append(SecretWordClass(title: "seychelles"))
        listOfCountries.append(SecretWordClass(title: "sierra leone"))
        listOfCountries.append(SecretWordClass(title: "singapore"))
        listOfCountries.append(SecretWordClass(title: "slovakia"))
        listOfCountries.append(SecretWordClass(title: "slovenia"))
        listOfCountries.append(SecretWordClass(title: "solomon islands"))
        listOfCountries.append(SecretWordClass(title: "somalia"))
        listOfCountries.append(SecretWordClass(title: "south africa"))
        listOfCountries.append(SecretWordClass(title: "spain"))
        listOfCountries.append(SecretWordClass(title: "sri lanka"))
        listOfCountries.append(SecretWordClass(title: "sudan"))
        listOfCountries.append(SecretWordClass(title: "south sudan"))
        listOfCountries.append(SecretWordClass(title: "suriname"))
        listOfCountries.append(SecretWordClass(title: "swaziland"))
        listOfCountries.append(SecretWordClass(title: "sweden"))
        listOfCountries.append(SecretWordClass(title: "switzerland"))
        listOfCountries.append(SecretWordClass(title: "syria"))
        
        // T (11 countries)
        listOfCountries.append(SecretWordClass(title: "taiwan"))
        listOfCountries.append(SecretWordClass(title: "tajikistan"))
        listOfCountries.append(SecretWordClass(title: "tanzania"))
        listOfCountries.append(SecretWordClass(title: "thailand"))
        listOfCountries.append(SecretWordClass(title: "togo"))
        listOfCountries.append(SecretWordClass(title: "tonga"))
        listOfCountries.append(SecretWordClass(title: "trinidad and tobago"))
        listOfCountries.append(SecretWordClass(title: "tunisia"))
        listOfCountries.append(SecretWordClass(title: "turkey"))
        listOfCountries.append(SecretWordClass(title: "turkmenistan"))
        listOfCountries.append(SecretWordClass(title: "tuvalu"))
        
        // U (7 countries)
        listOfCountries.append(SecretWordClass(title: "uganda"))
        listOfCountries.append(SecretWordClass(title: "ukraine"))
        listOfCountries.append(SecretWordClass(title: "united arab emirates"))
        listOfCountries.append(SecretWordClass(title: "united kingdom"))
        listOfCountries.append(SecretWordClass(title: "united states"))
        listOfCountries.append(SecretWordClass(title: "uruguay"))
        listOfCountries.append(SecretWordClass(title: "uzbekistan"))
        
        // V (4 countries)
        listOfCountries.append(SecretWordClass(title: "vanuatu"))
        listOfCountries.append(SecretWordClass(title: "vatican city"))
        listOfCountries.append(SecretWordClass(title: "venezuela"))
        listOfCountries.append(SecretWordClass(title: "vietnam"))
        
        // Y (1 country)
        listOfCountries.append(SecretWordClass(title: "Yemen"))
        
        // Z (
        listOfCountries.append(SecretWordClass(title: "zambia"))
        listOfCountries.append(SecretWordClass(title: "zimbabwe"))
    }
    
}
